export let accessToInsight = {
  constants: {
    rootUrl: "https://accesstoinsight.org",
    suffixUrl: "",
    chapterConnector: "",
  },
  dn: {
    format: ["sutta"],
    links: { card: "", all: "", main_page: "https://accesstoinsight.org/tipitaka/dn/index.html" },
    available: [
      [16, "/tipitaka/dn/dn.16.1-6.vaji.html"],
      [20, "/tipitaka/dn/dn.20.0.piya.html"],
      [22, "/tipitaka/dn/dn.22.0.bpit.html"],
      [31, "/tipitaka/dn/dn.31.0.nara.html"],
      [32, "/tipitaka/dn/dn.32.0.piya.html"],
    ],
  },
  mn: {
    format: ["sutta"],
    links: { all: "/", main_page: "https://accesstoinsight.org/tipitaka/mn/index.html" },
    available: [
      [2, "/tipitaka/mn/mn.002.bpit.html"],
      [7, "/tipitaka/mn/mn.007.nypo.html"],
      [8, "/tipitaka/mn/mn.008.nypo.html"],
      [10, "/tipitaka/mn/mn.010.soma.html"],
      [20, "/tipitaka/mn/mn.020.soma.html"],
      [22, "/tipitaka/mn/mn.022.nypo.html"],
      [59, "/tipitaka/mn/mn.059.nypo.html"],
      [107, "/tipitaka/mn/mn.107.horn.html"],
      [116, "/tipitaka/mn/mn.116.piya.html"],
      [125, "/tipitaka/mn/mn.125.horn.html"],
      [131, "/tipitaka/mn/mn.131.nana.html"],
      [141, "/tipitaka/mn/mn.141.piya.html"],
    ],
  },
  sn: {
    format: ["chapter"],
    links: { card: "", all: "", main_page: "https://accesstoinsight.org/tipitaka/sn/index.html" },
    available: {
      1: [[10, "/tipitaka/sn/sn01/sn01.010.irel.html"]],
      2: [
        [9, "/tipitaka/sn/sn02/sn02.009.piya.html"],
        [10, "/tipitaka/sn/sn02/sn02.010.piya.html"],
      ],

      7: [
        [2, "/tipitaka/sn/sn07/sn07.002.budd.html"],
        [11, "/tipitaka/sn/sn07/sn07.011.piya.html"],
      ],

      10: [[2, "/tipitaka/sn/sn10/sn10.012.piya.html"]],
      11: [[3, "/tipitaka/sn/sn11/sn11.003.piya.html"]],
      12: [
        [12, "/tipitaka/sn/sn12/sn12.012.nypo.html"],
        [63, "/tipitaka/sn/sn12/sn12.063.nypo.html"],
      ],
      22: [[59, "/tipitaka/sn/sn22/sn22.059.mend.html"]],

      36: [
        [1, "/tipitaka/sn/sn36/sn36.001.nypo.html"],
        [2, "/tipitaka/sn/sn36/sn36.002.nypo.html"],
        [3, "/tipitaka/sn/sn36/sn36.003.nypo.html"],
        [4, "/tipitaka/sn/sn36/sn36.004.nypo.html"],
        [5, "/tipitaka/sn/sn36/sn36.005.nypo.html"],
        [6, "/tipitaka/sn/sn36/sn36.006.nypo.html"],
        [7, "/tipitaka/sn/sn36/sn36.007.nypo.html"],
        [8, "/tipitaka/sn/sn36/sn36.008.nypo.html"],
        [9, "/tipitaka/sn/sn36/sn36.009.nypo.html"],
        [10, "/tipitaka/sn/sn36/sn36.010.nypo.html"],
        [11, "/tipitaka/sn/sn36/sn36.011.nypo.html"],
        [12, "/tipitaka/sn/sn36/sn36.012.nypo.html"],
        [14, "/tipitaka/sn/sn36/sn36.014.nypo.html"],
        [15, "/tipitaka/sn/sn36/sn36.015.nypo.html"],
        [19, "/tipitaka/sn/sn36/sn36.019.nypo.html"],
        [21, "/tipitaka/sn/sn36/sn36.021.nypo.html"],
        [22, "/tipitaka/sn/sn36/sn36.022.nypo.html"],
        [31, "/tipitaka/sn/sn36/sn36.031.nypo.html"],
      ],

      46: [
        [14, "/tipitaka/sn/sn46/sn46.014.piya.html"],
        [16, "/tipitaka/sn/sn46/sn46.016.piya.html"],
      ],
      47: [
        [13, "/tipitaka/sn/sn47/sn47.013.nypo.html"],
        [14, "/tipitaka/sn/sn47/sn47.014.nypo.html"],
      ],
      56: [[11, "/tipitaka/sn/sn56/sn56.011.piya.html"]],
    },
  },

  an: {
    format: ["chapter"],
    links: {
      main_page: "https://accesstoinsight.org/tipitaka/an/index.html",
      card: "",
      all: "",
    },
    available: {
      2: [[9, "/tipitaka/an/an02/an02.009.irel.html"]],
      3: [[65, "/tipitaka/an/an03/an03.065.soma.html"]],
      4: [
        [67, "/tipitaka/an/an04/an04.067.piya.html"],
        [95, "/tipitaka/an/an04/an04.095.budd.html"],
        [125, "/tipitaka/an/an04/an04.125.nymo.html"],
        [126, "/tipitaka/an/an04/an04.126.nymo.html"],
      ],
      5: [
        [49, "/tipitaka/an/an05/an05.049.hekh.html"],
        [161, "/tipitaka/an/an05/an05.161.nymo.html"],
      ],
      7: [[60, "/tipitaka/an/an07/an07.060.nymo.html"]],
      8: [
        [25, "/tipitaka/an/an08/an08.025.kuma.html"],
        [41, "/tipitaka/an/an08/an08.041.vaka.html"],
        [43, "/tipitaka/an/an08/an08.043.khan.html"],
        [54, "/tipitaka/an/an08/an08.054.nara.html"],
      ],
      10: [
        [48, "/tipitaka/an/an10/an10.048.piya.html"],
        [60, "/tipitaka/an/an10/an10.060.piya.html"],
      ],
      11: [[16, "/tipitaka/an/an11/an11.016.piya.html"]],
    },
  },
  kp: {
    format: ["sutta"],

    links: { card: "", all: "", main_page: "https://accesstoinsight.org/tipitaka/kn/khp/index.html" },
    available: [
      [1, "/tipitaka/kn/khp/khp.1-9x.piya.html#khp-1"],
      [2, "/tipitaka/kn/khp/khp.1-9x.piya.html#khp-2"],
      [3, "/tipitaka/kn/khp/khp.1-9x.piya.html#khp-3"],
      [4, "/tipitaka/kn/khp/khp.1-9x.piya.html#khp-4"],
      [5, "/tipitaka/kn/khp/khp.1-9x.piya.html#khp-5"],
      [6, "/tipitaka/kn/khp/khp.1-9x.piya.html#khp-6"],
      [9, "/tipitaka/kn/khp/khp.9.budd.html"],
    ],
  },
  dhp: {
    links: {
      card: "",
      all: "",
      main_page: "https://accesstoinsight.org/tipitaka/kn/dhp/index.html",
      chapter_links: {
        1: "/tipitaka/kn/dhp/dhp.01.budd.html",
        2: "/tipitaka/kn/dhp/dhp.02.budd.html",
        3: "/tipitaka/kn/dhp/dhp.03.budd.html",
        4: "/tipitaka/kn/dhp/dhp.04.budd.html",
        5: "/tipitaka/kn/dhp/dhp.05.budd.html",
        6: "/tipitaka/kn/dhp/dhp.06.budd.html",
        7: "/tipitaka/kn/dhp/dhp.07.budd.html",
        8: "/tipitaka/kn/dhp/dhp.08.budd.html",
        9: "/tipitaka/kn/dhp/dhp.09.budd.html",
        10: "/tipitaka/kn/dhp/dhp.10.budd.html",
        11: "/tipitaka/kn/dhp/dhp.11.budd.html",
        12: "/tipitaka/kn/dhp/dhp.12.budd.html",
        13: "/tipitaka/kn/dhp/dhp.13.budd.html",
        14: "/tipitaka/kn/dhp/dhp.14.budd.html",
        15: "/tipitaka/kn/dhp/dhp.15.budd.html",
        16: "/tipitaka/kn/dhp/dhp.16.budd.html",
        17: "/tipitaka/kn/dhp/dhp.17.budd.html",
        18: "/tipitaka/kn/dhp/dhp.18.budd.html",
        19: "/tipitaka/kn/dhp/dhp.19.budd.html",
        20: "/tipitaka/kn/dhp/dhp.20.budd.html",
        21: "/tipitaka/kn/dhp/dhp.21.budd.html",
        22: "/tipitaka/kn/dhp/dhp.22.budd.html",
        23: "/tipitaka/kn/dhp/dhp.23.budd.html",
        24: "/tipitaka/kn/dhp/dhp.24.budd.html",
        25: "/tipitaka/kn/dhp/dhp.25.budd.html",
        26: "/tipitaka/kn/dhp/dhp.26.budd.html",
      },
    },
    complete: true,
    range_suttas: [
      [1, 20],
      [21, 32],
      [33, 43],
      [44, 59],
      [60, 75],
      [76, 89],
      [90, 99],
      [100, 115],
      [116, 128],
      [129, 145],
      [146, 156],
      [157, 166],
      [167, 178],
      [179, 196],
      [197, 208],
      [209, 220],
      [221, 234],
      [235, 255],
      [256, 272],
      [273, 289],
      [290, 305],
      [306, 319],
      [320, 333],
      [334, 359],
      [360, 382],
      [383, 423],
    ],
    available: [
      [1, "/tipitaka/kn/dhp/dhp.01.budd.html"],
      [2, "/tipitaka/kn/dhp/dhp.02.budd.html"],
      [3, "/tipitaka/kn/dhp/dhp.03.budd.html"],
      [4, "/tipitaka/kn/dhp/dhp.04.budd.html"],
      [5, "/tipitaka/kn/dhp/dhp.05.budd.html"],
      [6, "/tipitaka/kn/dhp/dhp.06.budd.html"],
      [7, "/tipitaka/kn/dhp/dhp.07.budd.html"],
      [8, "/tipitaka/kn/dhp/dhp.08.budd.html"],
      [9, "/tipitaka/kn/dhp/dhp.09.budd.html"],
      [10, "/tipitaka/kn/dhp/dhp.10.budd.html"],
      [11, "/tipitaka/kn/dhp/dhp.11.budd.html"],
      [12, "/tipitaka/kn/dhp/dhp.12.budd.html"],
      [13, "/tipitaka/kn/dhp/dhp.13.budd.html"],
      [14, "/tipitaka/kn/dhp/dhp.14.budd.html"],
      [15, "/tipitaka/kn/dhp/dhp.15.budd.html"],
      [16, "/tipitaka/kn/dhp/dhp.16.budd.html"],
      [17, "/tipitaka/kn/dhp/dhp.17.budd.html"],
      [18, "/tipitaka/kn/dhp/dhp.18.budd.html"],
      [19, "/tipitaka/kn/dhp/dhp.19.budd.html"],
      [20, "/tipitaka/kn/dhp/dhp.20.budd.html"],
      [21, "/tipitaka/kn/dhp/dhp.21.budd.html"],
      [22, "/tipitaka/kn/dhp/dhp.22.budd.html"],
      [23, "/tipitaka/kn/dhp/dhp.23.budd.html"],
      [24, "/tipitaka/kn/dhp/dhp.24.budd.html"],
      [25, "/tipitaka/kn/dhp/dhp.25.budd.html"],
      [26, "/tipitaka/kn/dhp/dhp.26.budd.html"],
    ],
  },
  ud: {
    format: ["chapter", "sutta"],
    links: {
      card: "",
      all: "",
      main_page: "https://accesstoinsight.org/tipitaka/kn/ud/index.html",
    },
    complete: false,
    available: {
      1: [
        [1, "/tipitaka/kn/ud/ud.1.01.irel.html"],
        [2, "/tipitaka/kn/ud/ud.1.02.irel.html"],
        [3, "/tipitaka/kn/ud/ud.1.03.irel.html"],
        [10, "/tipitaka/kn/ud/ud.1.10.irel.html"],
      ],
      2: [
        [1, "/tipitaka/kn/ud/ud.2.01.irel.html"],
        [10, "/tipitaka/kn/ud/ud.2.10.irel.html"],
      ],
      3: [
        [1, "/tipitaka/kn/ud/ud.3.01.irel.html"],
        [2, "/tipitaka/kn/ud/ud.3.02.irel.html"],
      ],
      4: [
        [1, "/tipitaka/kn/ud/ud.4.01.irel.html"],
        [5, "/tipitaka/kn/ud/ud.4.05.irel.html"],
      ],
      5: [[5, "https://accesstoinsight.org/tipitaka/kn/ud/ud.5.05.irel.html"]],
      6: [[4, "https://accesstoinsight.org/tipitaka/kn/ud/ud.6.04.irel.html"]],
      7: [[9, "https://accesstoinsight.org/tipitaka/kn/ud/ud.7.09.irel.html"]],
      8: [
        [1, "/tipitaka/kn/ud/ud.8.01.irel.html"],
        [2, "/tipitaka/kn/ud/ud.8.02.irel.html"],
        [3, "/tipitaka/kn/ud/ud.8.03.irel.html"],
        [4, "/tipitaka/kn/ud/ud.8.04.irel.html"],
      ],
    },
  },
  snp: {
    format: ["chapter"],
    links: {
      card: "",
      all: "",
      main_page: "https://accesstoinsight.org/tipitaka/kn/snp/index.html",
    },
    available: {
      1: [
        [1, "/tipitaka/kn/snp/snp.1.01.nypo.html"],
        [4, "/tipitaka/kn/snp/snp.1.04.piya.html"],
        [6, "/tipitaka/kn/snp/snp.1.06.nara.html"],
        [7, "/tipitaka/kn/snp/snp.1.07.piya.htmll"],
        [8, "/tipitaka/kn/snp/snp.1.08.budd.html"],
        [10, "/tipitaka/kn/snp/snp.1.10.piya.html"],
      ],
      2: [
        [1, "/tipitaka/kn/snp/snp.2.01.piya.html"],
        [3, "/tipitaka/kn/snp/snp.2.03.irel.html"],
        [4, "/tipitaka/kn/snp/snp.2.04.nara.html"],
        [6, "/tipitaka/kn/snp/snp.2.06.irel.html"],
        [8, "/tipitaka/kn/snp/snp.2.08.irel.html"],
        [9, "/tipitaka/kn/snp/snp.2.09.irel.html"],
        [10, "/tipitaka/kn/snp/snp.2.10.irel.html"],
      ],
      3: [
        [2, "/tipitaka/kn/snp/snp.3.02.irel.html"],
        [8, "/tipitaka/kn/snp/snp.3.08.irel.html"],
      ],
      4: [
        [4, "/tipitaka/kn/snp/snp.4.04.irel.html"],
        [5, "/tipitaka/kn/snp/snp.4.05.irel.html"],
        [6, "/tipitaka/kn/snp/snp.4.06.irel.html"],
        [11, "/tipitaka/kn/snp/snp.4.11.irel.html"],
        [15, "/tipitaka/kn/snp/snp.4.15.irel.html"],
      ],
      5: [
        [1, "/tipitaka/kn/snp/snp.5.01.irel.html"],
        [3, "/tipitaka/kn/snp/snp.5.03.irel.html"],
        [4, "/tipitaka/kn/snp/snp.5.04.irel.html"],
        [15, "/tipitaka/kn/snp/snp.5.15.irel.html"],
        [16, "/tipitaka/kn/snp/snp.5.16.irel.html"],
      ],
    },
  },
};
