export let ancientBuddhistTexts = {
  constants: {
    rootUrl: "https://www.ancient-buddhist-texts.net",
    suffixUrl: "",
    chapterConnector: "",
  },
  dn: {
    format: ["sutta"],

    links: { card: "/long/dn", all: "/dn" },
    available: [
      [16, "/Texts-and-Translations/Mahaparinibbanasuttam/index.htm"],
      [22, "/Texts-and-Translations/Satipatthana/index.htm"],
    ],
  },
  mn: {
    format: ["sutta"],

    links: { all: "/MN/MN" },
    available: [
      [26, "/Texts-and-Translations/Ariyapariyesana/index.htm"],
      [44, "/Texts-and-Translations/Culavedalla/Culavedalla.htm"],
      [62, "/Texts-and-Translations/Short-Pieces/MahaRahulovadasuttam.htm"],
      [85, "/Texts-and-Translations/Bodhirajakumara/index.htm"],
      [98, "/Texts-and-Translations/Short-Pieces/Vasetthasuttam.htm"],
      [118, "/Texts-and-Translations/Anapanasati/index.htm"],
      [119, "/Texts-and-Translations/Kayagatasati/index.htm"],
      [141, "/Texts-and-Translations/Short-Pieces/Saccavibhangasuttam.htm"],
      [142, "/Texts-and-Translations/Short-Pieces/Dakkhinavibhangasuttam.htm"],
      [146, "/Texts-and-Translations/Nandakovada/Nandakovada.htm"],
    ],
  },
  sn: {
    format: ["chapter"],
    links: { card: "/linked/sn", all: "/sn" },
    available: {
      5: [
        [1, "/Texts-and-Translations/Bhikkhunisamyuttam/01-Alavika.htm", "1. The Discourse about Āḷavikā"],
        [2, "/Texts-and-Translations/Bhikkhunisamyuttam/02-Soma.htm", "2. The Discourse about Somā"],
        [3, "/Texts-and-Translations/Bhikkhunisamyuttam/03-Kisagotami.htm", "3. The Discourse about Kisāgotamī"],
        [4, "/Texts-and-Translations/Bhikkhunisamyuttam/04-Vijaya.htm", "4. The Discourse about Vijayā"],
        [5, "/Texts-and-Translations/Bhikkhunisamyuttam/05-Uppalavanna.htm", "5. The Discourse about Uppalavaṇṇā"],
        [6, "/Texts-and-Translations/Bhikkhunisamyuttam/06-Cala.htm", "6. The Discourse about Cālā"],
        [7, "/Texts-and-Translations/Bhikkhunisamyuttam/07-Upacala.htm", "7. The Discourse about Upacālā"],
        [8, "/Texts-and-Translations/Bhikkhunisamyuttam/08-Sisupacala.htm", "8. The Discourse about Sīsupacālā"],
        [9, "/Texts-and-Translations/Bhikkhunisamyuttam/09-Sela.htm", "9. The Discourse about Selā"],
        [10, "/Texts-and-Translations/Bhikkhunisamyuttam/10-Vajira.htm", "10. The Discourse about Vajirā"],
      ],
      12: [
        [
          2,
          "/Texts-and-Translations/Short-Pieces/Paticcasamuppadavibhangasuttam.htm",
          "2. The Discourse giving the Analysis (of Conditional Origination)",
        ],
      ],
      35: [
        [
          95,
          "/Texts-and-Translations/Short-Pieces/Malunkyaputtasuttam.htm",
          "95. The Discourse Concerning Māluṅkyaputta",
        ],
      ],
      44: [[1, "/Texts-and-Translations/Short-Pieces/Khemasuttam.htm", "1. The Discourse about Khemā"]],
      48: [
        [
          10,
          "/Texts-and-Translations/Short-Pieces/Indriyavibhangasuttam.htm",
          "The Second Discourse giving an Analysis [of the Faculties]",
        ],
      ],
      56: [
        [
          11,
          "/Texts-and-Translations/Short-Pieces/Dhammacakkappavattanasuttam.htm",
          "The Discourse that Set the Dhamma Wheel Rolling",
        ],
      ],
    },
  },

  an: {
    format: ["chapter"],
    links: { card: "/numbered/an", all: "/an" },
    available: {
      3: [[62, "/Texts-and-Translations/Short-Pieces/Titthayatanasuttam.htm", "62. The Belief Systems"]],
      4: [
        [61, "/Texts-and-Translations/Short-Pieces/Pattakammasuttam.htm", "61. he Discourse about Suitable Deeds"],
        [70, "/Texts-and-Translations/Short-Pieces/Adhammikasutta.htm", "70. The Discourse on the Dishonest"],
      ],
      5: [
        [41, "/Texts-and-Translations/Short-Pieces/Adiyasuttam.htm", "41. The Discourse on the Right Use (of Wealth)"],
      ],
      6: [[37, "/Texts-and-Translations/Short-Pieces/Chalangadana.htm", "37. The Six Factors of Giving"]],
      8: [
        [51, "/Texts-and-Translations/Gotamisuttani/01-Gotami.htm", "1. The Discourse concerning Gotamī"],
        [52, "/Texts-and-Translations/Gotamisuttani/02-Advising.htm", "2. The Discourse about Advising the Nuns"],
        [53, "/Texts-and-Translations/Gotamisuttani/03-Brief.htm", "3. The Discourse: ‘In Brief’"],
      ],
      10: [
        [60, "/Texts-and-Translations/Short-Pieces/Girimanandasuttam.htm", "60. The Discourse to Girimānanda"],
        [69, "/Texts-and-Translations/Short-Pieces/Kathavatthu.htm", "69. The First Discourse on the Bases for Talk"],
      ],
    },
  },

  kn: {
    format: ["sutta"],
    links: { card: "/minor/kn", all: "/kn" },
    available: [],
  },
  kp: {
    format: ["sutta"],
    links: {
      all: "/KN/Khp/khp",
      main_page: "https://www.ancient-buddhist-texts.net/Texts-and-Translations/Khuddakapatha/Khuddakapatha.htm",
    },
    available: [
      [1, "/Texts-and-Translations/Khuddakapatha/Khuddakapatha.htm"],
      [2, "/Texts-and-Translations/Khuddakapatha/Khuddakapatha.htm"],
      [3, "/Texts-and-Translations/Khuddakapatha/Khuddakapatha.htm"],
      [4, "/Texts-and-Translations/Khuddakapatha/Khuddakapatha.htm"],
      [5, "/Texts-and-Translations/Khuddakapatha/Khuddakapatha.htm"],
      [6, "/Texts-and-Translations/Khuddakapatha/Khuddakapatha.htm"],
      [7, "/Texts-and-Translations/Khuddakapatha/Khuddakapatha.htm"],
      [8, "/Texts-and-Translations/Khuddakapatha/Khuddakapatha.htm"],
      [9, "/Texts-and-Translations/Khuddakapatha/Khuddakapatha.htm"],
    ],
  },
  dhp: {
    links: {
      card: "/minor/dhp",
      all: "/dhp",
      main_page: "https://www.ancient-buddhist-texts.net/Texts-and-Translations/Dhammapada/index.htm",
      chapter_links: {
        1: "/Texts-and-Translations/Dhammapada/01-Pairs.htm",
        2: "/Texts-and-Translations/Dhammapada/02-Heedfulness.htm",
        3: "/Texts-and-Translations/Dhammapada/03-Mind.htm",
        4: "/Texts-and-Translations/Dhammapada/04-Flowers.htm",
        5: "/Texts-and-Translations/Dhammapada/05-Fools.htm",
        6: "/Texts-and-Translations/Dhammapada/06-Wise.htm",
        7: "/Texts-and-Translations/Dhammapada/07-Arahats.htm",
        8: "/Texts-and-Translations/Dhammapada/08-Thousands.htm",
        9: "/Texts-and-Translations/Dhammapada/09-Wickedness.htm",
        10: "/Texts-and-Translations/Dhammapada/10-Stick.htm",
        11: "/Texts-and-Translations/Dhammapada/11-Old-Age.htm",
        12: "/Texts-and-Translations/Dhammapada/12-Self.htm",
        13: "/Texts-and-Translations/Dhammapada/13-World.htm",
        14: "/Texts-and-Translations/Dhammapada/14-Buddha.htm",
        15: "/Texts-and-Translations/Dhammapada/15-Happiness.htm",
        16: "/Texts-and-Translations/Dhammapada/16-Love.htm",
        17: "/Texts-and-Translations/Dhammapada/17-Anger.htm",
        18: "/Texts-and-Translations/Dhammapada/18-Stains.htm",
        19: "/Texts-and-Translations/Dhammapada/19-Dhamma.htm",
        20: "/Texts-and-Translations/Dhammapada/20-Path.htm",
        21: "/Texts-and-Translations/Dhammapada/21-Miscellaneous.htm",
        22: "/Texts-and-Translations/Dhammapada/22-Underworld.htm",
        23: "/Texts-and-Translations/Dhammapada/23-Elephant.htm",
        24: "/Texts-and-Translations/Dhammapada/24-Craving.htm",
        25: "/Texts-and-Translations/Dhammapada/25-Monastics.htm",
        26: "/Texts-and-Translations/Dhammapada/26-Brahmins.htm",
      },
    },
    complete: true,
    range_suttas: [
      [1, 20],
      [21, 32],
      [33, 43],
      [44, 59],
      [60, 75],
      [76, 89],
      [90, 99],
      [100, 115],
      [116, 128],
      [129, 145],
      [146, 156],
      [157, 166],
      [167, 178],
      [179, 196],
      [197, 208],
      [209, 220],
      [221, 234],
      [235, 255],
      [256, 272],
      [273, 289],
      [290, 305],
      [306, 319],
      [320, 333],
      [334, 359],
      [360, 382],
      [383, 423],
    ],
    available: [
      [1, "/Texts-and-Translations/Dhammapada/01-Pairs.htm", "1. The Chapter about the Pairs (1-20)"],
      [2, "/Texts-and-Translations/Dhammapada/02-Heedfulness.htm", "2. The Chapter about Heedfulness (21-32)"],
      [3, "/Texts-and-Translations/Dhammapada/03-Mind.htm", "3. The Chapter about the Mind (33-43)"],
      [4, "/Texts-and-Translations/Dhammapada/04-Flowers.htm", "4. The Chapter about Flowers (44-59)"],
      [5, "/Texts-and-Translations/Dhammapada/05-Fools.htm", "5. The Chapter about Fools (60-75)"],
      [6, "/Texts-and-Translations/Dhammapada/06-Wise.htm", "6. The Chapter about the Wise (76-89)"],
      [7, "/Texts-and-Translations/Dhammapada/07-Arahats.htm", "7. The Chapter about the Arahats (90-99)"],
      [8, "/Texts-and-Translations/Dhammapada/08-Thousands.htm", "8. The Chapter about the Thousands (100-115)"],
      [9, "/Texts-and-Translations/Dhammapada/09-Wickedness.htm", "9. The Chapter about Wickedness (116-128)"],
      [10, "/Texts-and-Translations/Dhammapada/10-Stick.htm", "10. The Chapter about the Stick (129-145)"],
      [11, "/Texts-and-Translations/Dhammapada/11-Old-Age.htm", "11. The Chapter about Old Age (146-156)"],
      [12, "/Texts-and-Translations/Dhammapada/12-Self.htm", "12. The Chapter about the Self (157-166)"],
      [13, "/Texts-and-Translations/Dhammapada/13-World.htm", "13. The Chapter about the World (167-178)"],
      [14, "/Texts-and-Translations/Dhammapada/14-Buddha.htm", "14. The Chapter about the Buddha (179-196)"],
      [15, "/Texts-and-Translations/Dhammapada/15-Happiness.htm", "15. The Chapter about Happiness (197-208)"],
      [16, "/Texts-and-Translations/Dhammapada/16-Love.htm", "16. The Chapter about Love (209-220)"],
      [17, "/Texts-and-Translations/Dhammapada/17-Anger.htm", "17. The Chapter about Anger (221-234)"],
      [18, "/Texts-and-Translations/Dhammapada/18-Stains.htm", "18. The Chapter about Stains (235-255)"],
      [
        19,
        "/Texts-and-Translations/Dhammapada/19-Dhamma.htm",
        "19. The Chapter about One who stands by Dhamma (256-272)",
      ],
      [20, "/Texts-and-Translations/Dhammapada/20-Path.htm", "20. The Chapter about the Path (273-289)"],
      [21, "/Texts-and-Translations/Dhammapada/21-Miscellaneous.htm", "21. The Miscellaneous Chapter  (290-305)"],
      [22, "/Texts-and-Translations/Dhammapada/22-Underworld.htm", "22. The Chapter about the Underworld (306-319)"],
      [23, "/Texts-and-Translations/Dhammapada/23-Elephant.htm", "23. The Chapter about the Elephant (320-333)"],
      [24, "/Texts-and-Translations/Dhammapada/24-Craving.htm", "24. The Chapter about Craving (334-359)"],
      [25, "/Texts-and-Translations/Dhammapada/25-Monastics.htm", "25. The Chapter about Monastics (360-382)"],
      [26, "/Texts-and-Translations/Dhammapada/26-Brahmins.htm", "26. The Chapter about Brahmins (383-423)"],
    ],
  },
  ud: {
    format: ["chapter", "sutta"],
    links: {
      card: "/minor/kn/ud",
      all: "/ud",
      main_page: "https://www.ancient-buddhist-texts.net/Texts-and-Translations/Udana/index.htm",
    },
    complete: true,
    available: {
      1: [
        [1, "/Texts-and-Translations/Udana/1-Bodhivaggo-01.htm", "Pathamabodhisuttaṁ"],
        [2, "/Texts-and-Translations/Udana/1-Bodhivaggo-02.htm", "Dutiyabodhisuttaṁ"],
        [3, "/Texts-and-Translations/Udana/1-Bodhivaggo-03.htm", "Tatiyabodhisuttaṁ"],
        [4, "/Texts-and-Translations/Udana/1-Bodhivaggo-04.htm", "Nigrodhasuttaṁ"],
        [5, "/Texts-and-Translations/Udana/1-Bodhivaggo-05.htm", "Therasuttaṁ"],
        [6, "/Texts-and-Translations/Udana/1-Bodhivaggo-06.htm", "Kassapasuttaṁ"],
        [7, "/Texts-and-Translations/Udana/1-Bodhivaggo-07.htm", "Pāvāsuttaṁ"],
        [8, "/Texts-and-Translations/Udana/1-Bodhivaggo-08.htm", "Saṅgāmajīsuttaṁ"],
        [9, "/Texts-and-Translations/Udana/1-Bodhivaggo-09.htm", "Jaṭilasuttaṁ"],
        [10, "/Texts-and-Translations/Udana/1-Bodhivaggo-10.htm", "Bāhiyasuttaṁ"],
      ],
      2: [
        [1, "/Texts-and-Translations/Udana/2-Mucalindavaggo-01.htm", "Mucalindasuttaṁ"],
        [2, "/Texts-and-Translations/Udana/2-Mucalindavaggo-02.htm", "Rājasuttaṁ"],
        [3, "/Texts-and-Translations/Udana/2-Mucalindavaggo-03.htm", "Daṇḍasuttaṁ"],
        [4, "/Texts-and-Translations/Udana/2-Mucalindavaggo-04.htm", "Sakkārasuttaṁ"],
        [5, "/Texts-and-Translations/Udana/2-Mucalindavaggo-05.htm", "Upāsakasuttaṁ"],
        [6, "/Texts-and-Translations/Udana/2-Mucalindavaggo-06.htm", "Gabhinīsuttaṁ"],
        [7, "/Texts-and-Translations/Udana/2-Mucalindavaggo-07.htm", "Ekaputtasuttaṁ"],
        [8, "/Texts-and-Translations/Udana/2-Mucalindavaggo-08.htm", "Suppavāsāsuttaṁ"],
        [9, "/Texts-and-Translations/Udana/2-Mucalindavaggo-09.htm", "Visākhāsuttaṁ"],
        [10, "/Texts-and-Translations/Udana/2-Mucalindavaggo-10.htm", "Bhaddiyasuttaṁ"],
      ],
      3: [
        [1, "/Texts-and-Translations/Udana/3-Nandavaggo-01.htm", 1, "Kammasuttaṁ"],
        [2, "/Texts-and-Translations/Udana/3-Nandavaggo-02.htm", 2, "Nandasuttaṁ"],
        [3, "/Texts-and-Translations/Udana/3-Nandavaggo-03.htm", 3, "Yasojasuttaṁ"],
        [4, "/Texts-and-Translations/Udana/3-Nandavaggo-04.htm", 4, "Sāriputtasuttaṁ"],
        [5, "/Texts-and-Translations/Udana/3-Nandavaggo-05.htm", 5, "Kolitasuttaṁ"],
        [6, "/Texts-and-Translations/Udana/3-Nandavaggo-06.htm", 6, "Pilindivacchasuttaṁ"],
        [7, "/Texts-and-Translations/Udana/3-Nandavaggo-07.htm", 7, "Kassapasuttaṁ"],
        [8, "/Texts-and-Translations/Udana/3-Nandavaggo-08.htm", 8, "Piṇḍapātikasuttaṁ"],
        [9, "/Texts-and-Translations/Udana/3-Nandavaggo-09.htm", 9, "Sippasuttaṁ"],
        [10, "/Texts-and-Translations/Udana/3-Nandavaggo-10.htm", 10, "Lokavolokanasuttaṁ"],
      ],
      4: [
        [1, "/Texts-and-Translations/Udana/4-Meghiyavaggo-01.htm", "Meghiyasuttaṁ"],
        [2, "/Texts-and-Translations/Udana/4-Meghiyavaggo-02.htm", "Uddhatasuttaṁ"],
        [3, "/Texts-and-Translations/Udana/4-Meghiyavaggo-03.htm", "Gopālasuttaṁ"],
        [4, "/Texts-and-Translations/Udana/4-Meghiyavaggo-04.htm", "Juṇhasuttaṁ"],
        [5, "/Texts-and-Translations/Udana/4-Meghiyavaggo-05.htm", "Nāgasuttaṁ"],
        [6, "/Texts-and-Translations/Udana/4-Meghiyavaggo-06.htm", "Piṇḍolasuttaṁ"],
        [7, "/Texts-and-Translations/Udana/4-Meghiyavaggo-07.htm", "Sāriputtasuttaṁ"],
        [8, "/Texts-and-Translations/Udana/4-Meghiyavaggo-08.htm", "Sundarīsuttaṁ"],
        [9, "/Texts-and-Translations/Udana/4-Meghiyavaggo-09.htm", "Upasenasuttaṁ"],
        [10, "/Texts-and-Translations/Udana/4-Meghiyavaggo-10.htm", "Sāriputtasuttaṁ"],
      ],
      5: [
        [1, "/Texts-and-Translations/Udana/5-Sonavaggo-01-01.htm", "Rājasuttaṁ"],
        [2, "/Texts-and-Translations/Udana/5-Sonavaggo-01-02.htm", "Appāyukasuttaṁ"],
        [3, "/Texts-and-Translations/Udana/5-Sonavaggo-01-03.htm", "Suppabuddhakuṭṭhisuttaṁ"],
        [4, "/Texts-and-Translations/Udana/5-Sonavaggo-01-04.htm", "Kumārakasuttaṁ"],
        [5, "/Texts-and-Translations/Udana/5-Sonavaggo-01-05.htm", "Uposathasuttaṁ"],
        [6, "/Texts-and-Translations/Udana/5-Sonavaggo-01-06.htm", "Soṇasuttaṁ"],
        [7, "/Texts-and-Translations/Udana/5-Sonavaggo-01-07.htm", "Revatasuttaṁ"],
        [8, "/Texts-and-Translations/Udana/5-Sonavaggo-01-08.htm", "Ānandasuttaṁ"],
        [9, "/Texts-and-Translations/Udana/5-Sonavaggo-01-09.htm", "Saddhāyamānasuttaṁ"],
        [10, "/Texts-and-Translations/Udana/5-Sonavaggo-01-10.htm", "Panthakasuttaṁ"],
      ],
      6: [
        [1, "/Texts-and-Translations/Udana/6-Jaccandhavaggo-01.htm", "Āyusaṅkhāravossajanasuttaṁ"],
        [2, "/Texts-and-Translations/Udana/6-Jaccandhavaggo-02.htm", "Jaṭilasuttaṁ"],
        [3, "/Texts-and-Translations/Udana/6-Jaccandhavaggo-03.htm", "Paccavekkhanasuttaṁ"],
        [4, "/Texts-and-Translations/Udana/6-Jaccandhavaggo-04.htm", "Paṭhamanānātitthiyasuttaṁ"],
        [5, "/Texts-and-Translations/Udana/6-Jaccandhavaggo-05.htm", "Dutiyanānātitthiyasuttaṁ"],
        [6, "/Texts-and-Translations/Udana/6-Jaccandhavaggo-06.htm", "Tatiyanānātitthiyasuttaṁ"],
        [7, "/Texts-and-Translations/Udana/6-Jaccandhavaggo-07.htm", "Subhūtisuttaṁ"],
        [8, "/Texts-and-Translations/Udana/6-Jaccandhavaggo-08.htm", "Gaṇikāsuttaṁ"],
        [9, "/Texts-and-Translations/Udana/6-Jaccandhavaggo-09.htm", "Upātisuttaṁ"],
        [10, "/Texts-and-Translations/Udana/6-Jaccandhavaggo-10.htm", "Tathāgatuppādasuttaṁ"],
      ],
      7: [
        [1, "/Texts-and-Translations/Udana/7-Cullavaggo-01.htm", "Paṭhamabhaddiyasuttaṁ"],
        [2, "/Texts-and-Translations/Udana/7-Cullavaggo-02.htm", "Dutiyabhaddiyasuttaṁ"],
        [3, "/Texts-and-Translations/Udana/7-Cullavaggo-03.htm", "Sattasuttaṁ"],
        [4, "/Texts-and-Translations/Udana/7-Cullavaggo-04.htm", "Dutiyasattasuttaṁ"],
        [5, "/Texts-and-Translations/Udana/7-Cullavaggo-05.htm", "Lakuṇṭakabhaddiyasuttaṁ"],
        [6, "/Texts-and-Translations/Udana/7-Cullavaggo-06.htm", "Taṇhākkhayasuttaṁ"],
        [7, "/Texts-and-Translations/Udana/7-Cullavaggo-07.htm", "Papañcakkhayasuttaṁ"],
        [8, "/Texts-and-Translations/Udana/7-Cullavaggo-08.htm", "Kaccānasuttaṁ"],
        [9, "/Texts-and-Translations/Udana/7-Cullavaggo-09.htm", "Udapānasuttaṁ"],
        [10, "/Texts-and-Translations/Udana/7-Cullavaggo-10.htm", "Udenasuttaṁ"],
      ],
      8: [
        [1, "/Texts-and-Translations/Udana/8-Pataligamiyavaggo-01.htm", "Paṭhamanibbānasuttaṁ"],
        [2, "/Texts-and-Translations/Udana/8-Pataligamiyavaggo-02.htm", "Dutiyanibbānasuttaṁ"],
        [3, "/Texts-and-Translations/Udana/8-Pataligamiyavaggo-03.htm", "Tatiyanibbānasuttaṁ"],
        [4, "/Texts-and-Translations/Udana/8-Pataligamiyavaggo-04.htm", "Catutthanibbānasuttaṁ"],
        [5, "/Texts-and-Translations/Udana/8-Pataligamiyavaggo-05.htm", "Cundasuttaṁ"],
        [6, "/Texts-and-Translations/Udana/8-Pataligamiyavaggo-06.htm", "Pāṭaligāmiyasuttaṁ"],
        [7, "/Texts-and-Translations/Udana/8-Pataligamiyavaggo-07.htm", "Dvidhāpathasuttaṁ"],
        [8, "/Texts-and-Translations/Udana/8-Pataligamiyavaggo-08.htm", "Visākhāsuttaṁ"],
        [9, "/Texts-and-Translations/Udana/8-Pataligamiyavaggo-09.htm", "Paṭhamadabbasuttaṁ"],
        [10, "/Texts-and-Translations/Udana/8-Pataligamiyavaggo-10.htm", "Dutiyadabbasuttaṁ"],
      ],
    },
  },

  snp: {
    format: ["chapter"],
    links: {
      card: "/minor/kn/snp",
      all: "/snp",
      chapter_links: { 5: "/Texts-and-Translations/Parayanavagga/index.htm" },
    },
    available: {
      5: [
        [
          1,
          "/Texts-and-Translations/Parayanavagga/Parayanavaggo-01.htm",
          "Ajitamāṇavapucchā - Questions of the Young Man Ajita",
        ],
        [
          2,
          "/Texts-and-Translations/Parayanavagga/Parayanavaggo-02.htm",
          "Tissa-metteyyamāṇavapucchā - Questions of the Young Man Tissa Metteyya",
        ],
        [
          3,
          "/Texts-and-Translations/Parayanavagga/Parayanavaggo-03.htm",
          "Puṇṇakamāṇavapucchā - Questions of the Young Man Puṇṇaka",
        ],
        [
          4,
          "/Texts-and-Translations/Parayanavagga/Parayanavaggo-04.htm",
          "Mettagūmāṇavapucchā - Questions of the Young Man Mettagū",
        ],
        [
          5,
          "/Texts-and-Translations/Parayanavagga/Parayanavaggo-05.htm",
          "Dhotakamāṇavapucchā - Questions of the Young Man Dhotaka",
        ],
        [
          6,
          "/Texts-and-Translations/Parayanavagga/Parayanavaggo-06.htm",
          "Upasīvamāṇavapucchā - Questions of the Young Man Upasīva",
        ],
        [
          7,
          "/Texts-and-Translations/Parayanavagga/Parayanavaggo-07.htm",
          "Nandamāṇavapucchā - Questions of the Young Man Nanda",
        ],
        [
          8,
          "/Texts-and-Translations/Parayanavagga/Parayanavaggo-08.htm",
          "Hemakamāṇavapucchā - Questions of the Young Man Hemaka",
        ],
        [
          9,
          "/Texts-and-Translations/Parayanavagga/Parayanavaggo-09.htm",
          "Todeyyamāṇavapucchā - Questions of the Young ManTodeyya",
        ],
        [
          10,
          "/Texts-and-Translations/Parayanavagga/Parayanavaggo-10.htm",
          "Kappamāṇavapucchā - Questions of the Young Man Kappa",
        ],
        [
          11,
          "/Texts-and-Translations/Parayanavagga/Parayanavaggo-11.htm",
          "Jatukaṇṇīmāṇavapucchā - Questions of the Young Man Jatukaṇṇī",
        ],
        [
          12,
          "/Texts-and-Translations/Parayanavagga/Parayanavaggo-12.htm",
          "Bhadrāvudhamāṇavapucchā - Questions of the Young Man Bhadrāvudha",
        ],
        [
          13,
          "/Texts-and-Translations/Parayanavagga/Parayanavaggo-13.htm",
          "Udayamāṇavapucchā - Questions of the Young Man Udaya",
        ],
        [
          14,
          "/Texts-and-Translations/Parayanavagga/Parayanavaggo-14.htm",
          "Posālamāṇavapucchā - Questions of the Young Man Posāla",
        ],
        [
          15,
          "/Texts-and-Translations/Parayanavagga/Parayanavaggo-15.htm",
          "Mogharājamāṇavapucchā - Questions of the Young Man Mogharāja",
        ],
        [
          16,
          "/Texts-and-Translations/Parayanavagga/Parayanavaggo-16.htm",
          "Piṅgiyamāṇavapucchā - Questions of the Young Man Piṅgiya",
        ],
      ],
    },
  },

  ja: {
    available: [],
    links: {
      card: "/minor/kn/thig",
      all: "/thig",
      main_page: "https://www.ancient-buddhist-texts.net/English-Texts/Jataka/index.htm#gsc.tab=0",
    },
  },
};
